FROM golang:1.22.10-bullseye
LABEL authors="daheige"

# 设置环境变量
ENV LANG="zh_CN.UTF-8"

# 设置nodejs版本
ENV NODEJS_VERSION=20

WORKDIR /app

# 设置deb镜像源，这里我使用aliyun的镜像
RUN echo "deb http://mirrors.aliyun.com/debian bullseye main" > /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian-security bullseye-security main" >> /etc/apt/sources.list &&  \
    echo "deb http://mirrors.aliyun.com/debian bullseye-updates main" >> /etc/apt/sources.list &&  \
    apt-get update && apt-get install -y ca-certificates gcc cmake make libtool vim bash curl net-tools wget \
    git net-tools iputils-ping protobuf-compiler libprotobuf-dev apt-transport-https && \
    curl -fsSL https://deb.nodesource.com/setup_$NODEJS_VERSION.x -o nodesource_setup.sh && \
    chmod +x ./nodesource_setup.sh && \
    ./nodesource_setup.sh && apt-get install nodejs -y \
    && update-ca-certificates && apt-get clean &&  \
    rm -rf /var/lib/apt/lists/* \
    && go install github.com/cloudwego/kitex/tool/cmd/kitex@latest \
    && go install github.com/cloudwego/protoc-gen-validator@latest \
    && go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

CMD ["bash"]
