// Code generated by Kitex v0.13.0. DO NOT EDIT.

package pb

import (
	"context"

	"github.com/cloudwego/prutal"
)

type HelloRequest struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (x *HelloRequest) Reset() { *x = HelloRequest{} }

func (x *HelloRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HelloRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HelloRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HelloReply struct {
	Id  int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (x *HelloReply) Reset() { *x = HelloReply{} }

func (x *HelloReply) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *HelloReply) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *HelloReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HelloReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Greeter interface {
	Hello(ctx context.Context, req *HelloRequest) (res *HelloReply, err error)
}
